package de.timmi6790.basemod.values.bukkit;

public enum BukkitEnchantments {
    ARROW_DAMAGE,
    ARROW_FIRE,
    ARROW_INFINITE,
    ARROW_KNOCKBACK,
    DAMAGE_ALL,
    DAMAGE_ARTHROPODS,
    DAMAGE_UNDEAD,
    DIG_SPEED,
    DURABILITY,
    FIRE_ASPECT,
    KNOCKBACK,
    LOOT_BONUS_BLOCKS,
    LOOT_BONUS_MOBS,
    LUCK,
    LURE,
    PROTECTION_ENVIRONMENTAL,
    THORNS,
    PROTECTION_EXPLOSIONS,
    PROTECTION_FALL,
    PROTECTION_FIRE,
    PROTECTION_PROJECTILE,
    SILK_TOUCH
}
