package de.timmi6790.mpmod.values;

public class MineplexValues {
    private static final String[] COSMETICS = {"EtherealPearl", "Fireworks", "TNT", "MelonLauncher", "FleshHook",
            "PaintballGun", "BatBlaster", "TreasurePartyBomb", "Paintbrush", "PvPSword", "PartyPopper", "Coal",
            "FreezeCannon", "Snowball", "Cupid'sArrows", "LovePotion", "ValentinesGift", "HalloweenCandy", "TicTacToe",
            "MobBomb", "PlayCatch", "Trampoline", "Connect4", "Nanny'sUmbrella", "ClackerBoomerang", "GateofBabylon",
            "GrapplingHook", "Spook-in-a-box", "Fromthedepths...", "PortalGun", "SnowGun", "FestiveRelics",
            "ChocolateGun", "LoveLetters", "Jetpack", "Stormbreaker", "BakersDelight", "HumanFirework", "CloneBone",
            "SummoningRitual", "AirSpout", "VillagerMorph", "CowMorph", "ChickenMorph", "BlockMorph", "EndermanMorph",
            "BatMorph", "PumpkinKingsHead", "PigMorph", "CreeperMorph", "BlazeMorph", "WitherMorph", "EasterBunnyMorph",
            "BigLarryMorph", "ElderGuardianMorph", "OlafMorph", "UncleSamMorph", "SquidMorph", "WitchMorph",
            "GrimReaperMorph", "MetalManMorph", "TurkeyMorph", "ChristmasKingsHead", "SantaMorph", "OverEasyMorph",
            "LoveDoctor", "GoldPotMorph", "WascallyWabbitMorph", "BobRossMorph", "FreedomFighter", "MelonheadMorph",
            "HattoriMorph", "DevonMorph", "AnathMorph", "DanaMorph", "BardolfMorph", "RowenaMorph", "LarissaMorph",
            "BiffMorph", "IvyMorph", "GhastMorph", "FrostGolemMorph", "SkeletonMorph", "OcelotMorph", "WolfMorph",
            "PigmanMorph", "GraveMorph", "WinterPrincess", "CraigtheKangaroo", "CupidMorph", "Area51GuardMorph",
            "ShadowWalk", "EmeraldTwirl", "RainCloud", "BloodHelix", "Enchanted", "Music", "PartyTime", "Cupid'sLove",
            "CrushedCandyCane", "WindoftheFrostLord", "LegendaryAura", "FlameoftheTitans", "YinandYang", "King",
            "PixieWings", "DemonWings", "InfernalWings", "AngelWings", "LoveWings", "FlameRings", "FlameFairy",
            "HolidayTree", "CoalFumes", "SpringHalo", "Bumblebee'sWings", "FreedomAura", "FreedomFireworks",
            "StarSpangledStripe", "AuraofNiceness", "CanadianTrail", "HalloweenAura", "ChristmasWings", "BlizzardAura",
            "FidgetSpinnerAura", "PumpkinShield", "RainbowAura", "MacawWings", "ChickenWings", "EnderDragon",
            "FoxTail", "JetPack", "MineplexCape", "LegendaryHero", "WolfTail", "Witch'sCurse", "TrailoftheRainbow",
            "DeepSeaSwirl", "CollidingColors", "FiveYearsofMineplex", "WitherWinds", "IceColdDome",
            "Tis'TheSeasonforHelping", "BeatingHeart", "ClashoftheCakes", "13Disc", "CatDisc", "BlocksDisc",
            "ChirpDisc", "FarDisc", "MallDisc", "MellohiDisc", "StalDisc", "StradDisc", "WardDisc", "WaitDisc",
            "RaveHat", "RaveShirt", "RavePants", "RaveBoots", "SpaceHelmet", "SpaceJacket", "SpacePants", "SpaceBoots",
            "FreezeHelmet", "FreezeChest", "FreezeLeggings", "FreezeBoots", "Leprechaun'sHat", "Leprechaun'sChest",
            "Leprechaun'sPants", "Leprechaun'sBoots", "ReindeerAntlers", "ReindeerChest", "ReindeerLegs",
            "ReindeerHooves", "WindupHelmet", "WindupChestplate", "WindupLeggings", "WindupBoots", "WitchHead",
            "WitchChest", "WitchLegs", "WitchBoots", "TeamHelmet", "TeamShirt", "TeamPants", "TeamBoots",
            "GustoftheFrostLord", "LeapoftheTitans", "CandyCaneBlast", "FirecrackerLeap", "Cupid'sWings", "GreenJump",
            "ShadowLeap", "LeapofWisdom", "WetLeap", "BloodyLeap", "MusicalLeap", "LeapofFreedom", "Trick-Or-Leap",
            "FlowerPower", "MapleLeap", "PresentLeap", "RainbowLeap", "LegendaryLeap", "BalancedLeap",
            "IceColdDoubleJump", "HeartLeap", "ArrowsoftheFrostLord", "ArrowsoftheTitans", "CandyCaneArrows",
            "ArrowConfetti", "Cupid'sArrows", "GreenArrows", "ShadowArrows", "SmartArrows", "RainArrows",
            "BloodyArrows", "MusicArrows", "ShockandAwe", "HalloweenArrows", "FlowerArrows", "Red&WhiteArrows",
            "PresentArrows", "RainbowArrows", "ArrowsoftheLegends", "SimpleGeometry", "IceColdArrowTrail",
            "HeartArrowTrail", "FalloftheFrostLord", "AshesoftheTitans", "CandyCaneRemains", "PinataBurst",
            "Cupid'sBrokenHeart", "GreenDeath", "ShadowDeath", "DeathofWisdom", "GloomyDeath", "GoryBloodDeath",
            "MusicalDeath", "PriceofFreedom", "PresentDanger", "FuneralBouquet", "FallenMapleLeaf", "SpookyDeath",
            "RainbowDeath", "Legend'sLegacy", "Everlastingbalance", "Ghost", "IceColdDeath", "HeartDeath",
            "LumpofCoalHat", "CompanionBlock", "TheGrinch", "LoveStruck", "Present", "Rudolph", "Santa",
            "SecretPackage", "SnowmanHead", "TeddyBear", "UncleSamHat", "PumpkinHat", "WarmCanadianHat",
            "PatrioticAmericanHat", "PottedAzalea", "EternalTaunt", "BlowAKiss", "RainbowTaunt", "InfernalTaunt",
            "FrostBreathTaunt", "EmojiTaunt", "EasyModeTaunt", "ChickenTaunt", "TrickorTreat", "SnowballFight",
            "GloatingGardenerTaunt", "Podium", "MineplexLogo", "Mr.Punchman", "Flames", "SnowTrail", "BabyChicken",
            "LightningStrike", "RiseoftheElderGuardian", "LavaTrap", "ReturnofThePumpkin", "WinterWarfare",
            "LoveisaBattlefield", "Tornado", "Earthquake", "PartyAnimal", "SnowGlobe", "NewYearCelebrations",
            "HoppingSurprise", "UltraWinEffect", "HeroWinEffect", "LegendWinEffect", "TitanWinEffect",
            "EternalWinEffect", "P250Muertos", "CZ75-AutoTigris", "DesertEagleBlaze", "GoldenGun",
            "P2000FireElemental", "Glock18Fade", "NovaKoi", "XM1014Tranquility", "XM1014PigGun", "PP-BizonStreak",
            "P90Asiimov", "FAMASPulse", "M4A4Howl", "EndermanM4", "GalilAREco", "AK-47Vulcan", "GuardianAK",
            "SSG08BloodintheWater", "AWPAsiimov", "SteyrAUGTorque", "SG553Pulse", "M9BayonetFade",
            "CounterTerroristSword", "TerroristSword", "GlassM9Bayonet", "2017ChampionshipKnife",
            "Orange(Bardolf-Werewolf)", "Blue(Bardolf-Werewolf)", "Green(Bardolf-Werewolf)", "Yellow(Bardolf-Werewolf)",
            "Pink(Dana)", "Blue(Dana)", "Brown(Dana)", "Green(Dana)", "Pristine(Dana)", "Wonderful(Dana)",
            "Heroic(Dana)", "Green(Hattori)", "White(Hattori)", "Purple(Hattori)", "Blue(Hattori)", "Red(Larissa)",
            "Pink(Larissa)", "Green(Larissa)", "Yellow(Larissa)", "Green(Biff)", "Purple(Biff)", "Orange(Biff)",
            "Blue(Biff)", "Soulless(Biff)", "Sanctified(Biff)", "BiffSmash!(Biff)", "Demonic(Biff)", "FancyBiff(Biff)",
            "DapperBiff(Biff)", "Brown(Devon)", "Blue(Devon)", "Yellow(Devon)", "Silver(Devon)", "Amethyst(Devon)",
            "Chalk(Devon)", "Orange(Bardolf)", "Blue(Bardolf)", "Green(Bardolf)", "Yellow(Bardolf)", "Purple(Anath)",
            "Yellow(Anath)", "Red(Anath)", "Blue(Anath)", "Light(Anath)", "Shadow(Anath)", "Unburnt(Anath)",
            "CourtMage(Anath)", "MaskedMage(Anath)", "CultMage(Anath)", "Brown(Rowena)", "Blue(Rowena)",
            "Purple(Rowena)", "Red(Rowena)", "Thundercloud(Rowena)", "SheepShopSkin", "CowShopSkin",
            "MooshroomShopSkin", "PigShopSkin", "HorseShopSkin", "SnowmanShopSkin", "IronGolemShopSkin",
            "ZombieShopSkin", "SkeletonShopSkin", "CreeperShopSkin", "SpiderShopSkin", "SlimeShopSkin",
            "MagmaSlimeShopSkin", "WitherSkeletonShopSkin", "PigZombieShopSkin", "WitchShopSkin", "BlazeShopSkin",
            "GuardianShopSkin", "EndermanShopSkin", "SantaShopSkin", "BobRossShopSkin", "FreedomFighterShopSkin",
            "BabyCowBalloon", "BabyPigBalloon", "BabyZombieBalloon", "BabyMushroomCowBalloon", "BabyOcelotBalloon",
            "BabyWolfBalloon", "BabySheepBalloon", "BabyVillagerBalloon", "BabySlimeBalloon", "SquidBalloon",
            "BatBalloon", "SilverfishBalloon", "GuardianBalloon", "DragonEggBalloon", "DiamondBlockBalloon",
            "IronBlockBalloon", "GoldBlockBalloon", "EmeraldBlockBalloon", "RedBalloon", "IceBlockBalloon",
            "CompanionCubeBalloon", "HeartBalloon", "WaterWings", "Halo", "RainbowDance", "RainCloud",
            "ShimmeringRing", "HauntedKit", "BlissfulAstroid", "FlamesOfFury", "Ember", "KitLove", "FlagofCanada",
            "FlagofTheUnitedStatesofAmerica", "FlagofMineplex", "FlagofRudolph", "FlagofChristmasTree",
            "FlagofPresent", "FlagofWreath", "FlagofSnowFlake", "FlagofHeart", "FlagofSpringFlower", "InfernalHorror",
            "GlacialSteed", "MountMule", "EtherealDragon", "SlimeMount", "Minecart", "SpiderMount", "DecrepitWarhorse",
            "MoltenSnake", "BabyReindeer", "LovingSheeples", "FreedomMount", "NightmareSteed", "ChickenMount",
            "CakeMount", "LoveTrain", "RainbowHorse", "PumpkinMount", "SledgeMount", "HeadlessHorseman",
            "SnowmanMount", "Splinter", "Thorn", "Kevin'sLostToothpick", "Striker", "ThornBush", "HowlingSword",
            "QuickBlade", "Winterthorn", "Needle", "Longsword", "Whisper", "Bruiser", "HeartoftheMountain",
            "Quern-Biter", "GravenEdge", "Protector", "GhostReaver", "Skullcrusher", "Ragnarok", "Warmonger",
            "Gutrender", "FrostyGreatsword", "Shadowstrike", "Tenderizer", "GoldDigger", "Peacekeeper", "Gladius",
            "Ghostwalker", "Scar", "Burn", "SunStrike", "MageBlade", "FlamingRapier", "AlienArtifact", "Stormbringer",
            "Sting", "Dragonfire", "Hope'sEnd", "Doombringer", "StormCaller", "BlackOut", "IceHeart", "OoohShiny",
            "Dragonslayer", "Oblivion", "Deathraze", "Oathbreaker", "Vanquisher", "NoblePhantasm", "SweetVictory",
            "RainbowRoad", "No.2Pencil", "GrayLevelColor", "BlueLevelColor", "DarkGreenLevelColor", "GoldLevelColor",
            "RedLevelColor", "DarkRedLevelColor", "YellowLevelColor", "GreenLevelColor", "AquaLevelColor",
            "CyanLevelColor", "DarkBlueLevelColor", "PurpleLevelColor", "PinkLevelColor", "WhiteLevelColor",
            "BlackLevelColor"};

    public static String[] getCosmetics() {
        return COSMETICS.clone();
    }
}
