package de.timmi6790.mcmod.values;

public class BukkitValues {
    private static final String[] ENCHANTMENTS = {"ARROW_DAMAGE", "ARROW_FIRE", "ARROW_INFINITE", "ARROW_KNOCKBACK",
            "DAMAGE_ALL", "DAMAGE_ARTHROPODS", "DAMAGE_UNDEAD", "DIG_SPEED", "DURABILITY", "FIRE_ASPECT", "KNOCKBACK",
            "LOOT_BONUS_BLOCKS", "LOOT_BONUS_MOBS", "LUCK", "LURE", "PROTECTION_ENVIRONMENTAL", "THORNS",
            "PROTECTION_EXPLOSIONS", "PROTECTION_FALL", "PROTECTION_FIRE", "PROTECTION_PROJECTILE", "SILK_TOUCH"};

    private static final String[] MOBS = {"Item", "Arrow", "WitherSkull", "Creeper", "Skeleton", "Spider", "Giant",
            "Zombie", "Slime", "Ghast", "PigZombie", "Enderman", "Cave", "Silverfish", "Blaze", "LavaSlime", "Dragon",
            "Wither", "Bat", "Witch", "Guardian", "Pig", "Sheep", "Cow", "Chicken", "Squid", "Wolf", "MushroomCow",
            "SnowMan", "Ozelot", "Golem", "Horse", "Rabbit"};

    private static final String[] EFFECTS = {"SPEED", "SLOW", "FAST_DIGGING", "SLOW_DIGGING", "INCREASE_DAMAGE", "HEAL", "HARM", "JUMP",
            "CONFUSION", "REGENERATION", "DAMAGE_RESISTANCE", "FIRE_RESISTANCE", "WATER_BREATHING", "INVISIBILITY", "BLINDNESS", "NIGHT_VISION",
            "HUNGER", "WEAKNESS", "POISON", "WITHER", "HEALTH_BOOST", "ABSORPTION", "SATURATION", "GLOWING", "LEVITATION"};

    private static final String[] MATERIALS = {"AIR", "STONE", "GRASS", "DIRT", "COBBLESTONE", "WOOD", "SAPLING",
            "BEDROCK", "WATER", "STATIONARY_WATER", "LAVA", "STATIONARY_LAVA", "SAND", "GRAVEL", "GOLD_ORE", "IRON_ORE",
            "COAL_ORE", "LOG", "LEAVES", "SPONGE", "GLASS", "LAPIS_ORE", "LAPIS_BLOCK", "DISPENSER", "SANDSTONE",
            "NOTE_BLOCK", "BED_BLOCK", "POWERED_RAIL", "DETECTOR_RAIL", "PISTON_STICKY_BASE", "WEB", "LONG_GRASS",
            "DEAD_BUSH", "PISTON_BASE", "PISTON_EXTENSION", "WOOL", "PISTON_MOVING_PIECE", "YELLOW_FLOWER", "RED_ROSE",
            "BROWN_MUSHROOM", "RED_MUSHROOM", "GOLD_BLOCK", "IRON_BLOCK", "DOUBLE_STEP", "STEP", "BRICK", "TNT",
            "BOOKSHELF", "MOSSY_COBBLESTONE", "OBSIDIAN", "TORCH", "FIRE", "MOB_SPAWNER", "WOOD_STAIRS", "CHEST",
            "REDSTONE_WIRE", "DIAMOND_ORE", "DIAMOND_BLOCK", "WORKBENCH", "CROPS", "SOIL", "FURNACE", "BURNING_FURNACE",
            "SIGN_POST", "WOODEN_DOOR", "LADDER", "RAILS", "COBBLESTONE_STAIRS", "WALL_SIGN", "LEVER", "STONE_PLATE",
            "IRON_DOOR_BLOCK", "WOOD_PLATE", "REDSTONE_ORE", "GLOWING_REDSTONE_ORE", "REDSTONE_TORCH_OFF",
            "REDSTONE_TORCH_ON", "STONE_BUTTON", "SNOW", "ICE", "SNOW_BLOCK", "CACTUS", "CLAY", "SUGAR_CANE_BLOCK",
            "JUKEBOX", "FENCE", "PUMPKIN", "NETHERRACK", "SOUL_SAND", "GLOWSTONE", "PORTAL", "JACK_O_LANTERN",
            "CAKE_BLOCK", "DIODE_BLOCK_OFF", "DIODE_BLOCK_ON", "LOCKED_CHEST", "STAINED_GLASS", "TRAP_DOOR",
            "MONSTER_EGGS", "SMOOTH_BRICK", "HUGE_MUSHROOM_1", "HUGE_MUSHROOM_2", "IRON_FENCE", "THIN_GLASS",
            "MELON_BLOCK", "PUMPKIN_STEM", "MELON_STEM", "VINE", "FENCE_GATE", "BRICK_STAIRS", "SMOOTH_STAIRS",
            "MYCEL", "WATER_LILY", "NETHER_BRICK", "NETHER_FENCE", "NETHER_BRICK_STAIRS", "NETHER_WARTS",
            "ENCHANTMENT_TABLE", "BREWING_STAND", "CAULDRON", "ENDER_PORTAL", "ENDER_PORTAL_FRAME", "ENDER_STONE",
            "DRAGON_EGG", "REDSTONE_LAMP_OFF", "REDSTONE_LAMP_ON", "WOOD_DOUBLE_STEP", "WOOD_STEP", "COCOA",
            "SANDSTONE_STAIRS", "EMERALD_ORE", "ENDER_CHEST", "TRIPWIRE_HOOK", "TRIPWIRE", "EMERALD_BLOCK",
            "SPRUCE_WOOD_STAIRS", "BIRCH_WOOD_STAIRS", "JUNGLE_WOOD_STAIRS", "COMMAND", "BEACON", "COBBLE_WALL",
            "FLOWER_POT", "CARROT", "POTATO", "WOOD_BUTTON", "SKULL", "ANVIL", "TRAPPED_CHEST", "GOLD_PLATE",
            "IRON_PLATE", "REDSTONE_COMPARATOR_OFF", "REDSTONE_COMPARATOR_ON", "DAYLIGHT_DETECTOR", "REDSTONE_BLOCK",
            "QUARTZ_ORE", "HOPPER", "QUARTZ_BLOCK", "QUARTZ_STAIRS", "ACTIVATOR_RAIL", "DROPPER", "STAINED_CLAY",
            "STAINED_GLASS_PANE", "LEAVES_2", "LOG_2", "ACACIA_STAIRS", "DARK_OAK_STAIRS", "HAY_BLOCK", "CARPET",
            "HARD_CLAY", "COAL_BLOCK", "PACKED_ICE", "DOUBLE_PLANT", "IRON_SPADE", "IRON_PICKAXE", "IRON_AXE",
            "FLINT_AND_STEEL", "APPLE", "BOW", "ARROW", "COAL", "DIAMOND", "IRON_INGOT", "GOLD_INGOT", "IRON_SWORD",
            "WOOD_SWORD", "WOOD_SPADE", "WOOD_PICKAXE", "WOOD_AXE", "STONE_SWORD", "STONE_SPADE", "STONE_PICKAXE",
            "STONE_AXE", "DIAMOND_SWORD", "DIAMOND_SPADE", "DIAMOND_PICKAXE", "DIAMOND_AXE", "STICK", "BOWL",
            "MUSHROOM_SOUP", "GOLD_SWORD", "GOLD_SPADE", "GOLD_PICKAXE", "GOLD_AXE", "STRING", "FEATHER", "SULPHUR",
            "WOOD_HOE", "STONE_HOE", "IRON_HOE", "DIAMOND_HOE", "GOLD_HOE", "SEEDS", "WHEAT", "BREAD", "LEATHER_HELMET",
            "LEATHER_CHESTPLATE", "LEATHER_LEGGINGS", "LEATHER_BOOTS", "CHAINMAIL_HELMET", "CHAINMAIL_CHESTPLATE",
            "CHAINMAIL_LEGGINGS", "CHAINMAIL_BOOTS", "IRON_HELMET", "IRON_CHESTPLATE", "IRON_LEGGINGS", "IRON_BOOTS",
            "DIAMOND_HELMET", "DIAMOND_CHESTPLATE", "DIAMOND_LEGGINGS", "DIAMOND_BOOTS", "GOLD_HELMET",
            "GOLD_CHESTPLATE", "GOLD_LEGGINGS", "GOLD_BOOTS", "FLINT", "PORK", "GRILLED_PORK", "PAINTING",
            "GOLDEN_APPLE", "SIGN", "WOOD_DOOR", "BUCKET", "WATER_BUCKET", "LAVA_BUCKET", "MINECART", "SADDLE",
            "IRON_DOOR", "REDSTONE", "SNOW_BALL", "BOAT", "LEATHER", "MILK_BUCKET", "CLAY_BRICK", "CLAY_BALL",
            "SUGAR_CANE", "PAPER", "BOOK", "SLIME_BALL", "STORAGE_MINECART", "POWERED_MINECART", "EGG", "COMPASS",
            "FISHING_ROD", "WATCH", "GLOWSTONE_DUST", "RAW_FISH", "COOKED_FISH", "INK_SACK", "BONE", "SUGAR", "CAKE",
            "BED", "DIODE", "COOKIE", "MAP", "SHEARS", "MELON", "PUMPKIN_SEEDS", "MELON_SEEDS", "RAW_BEEF",
            "COOKED_BEEF", "RAW_CHICKEN", "COOKED_CHICKEN", "ROTTEN_FLESH", "ENDER_PEARL", "BLAZE_ROD", "GHAST_TEAR",
            "GOLD_NUGGET", "NETHER_STALK", "POTION", "GLASS_BOTTLE", "SPIDER_EYE", "FERMENTED_SPIDER_EYE",
            "BLAZE_POWDER", "MAGMA_CREAM", "BREWING_STAND_ITEM", "CAULDRON_ITEM", "EYE_OF_ENDER", "SPECKLED_MELON",
            "MONSTER_EGG", "EXP_BOTTLE", "FIREBALL", "BOOK_AND_QUILL", "WRITTEN_BOOK", "EMERALD", "ITEM_FRAME",
            "FLOWER_POT_ITEM", "CARROT_ITEM", "POTATO_ITEM", "BAKED_POTATO", "POISONOUS_POTATO", "EMPTY_MAP",
            "GOLDEN_CARROT", "SKULL_ITEM", "CARROT_STICK", "NETHER_STAR", "PUMPKIN_PIE", "FIREWORK", "FIREWORK_CHARGE",
            "ENCHANTED_BOOK", "REDSTONE_COMPARATOR", "NETHER_BRICK_ITEM", "QUARTZ", "EXPLOSIVE_MINECART",
            "HOPPER_MINECART", "IRON_BARDING", "GOLD_BARDING", "DIAMOND_BARDING", "LEASH", "NAME_TAG",
            "COMMAND_MINECART", "GOLD_RECORD", "GREEN_RECORD", "RECORD_3", "RECORD_4", "RECORD_5", "RECORD_6",
            "RECORD_7", "RECORD_8", "RECORD_9", "RECORD_10", "RECORD_11", "RECORD_12"};

    private static final String[] COSMETICS = {"EtherealPearl", "Fireworks", "TNT", "MelonLauncher", "FleshHook",
            "PaintballGun", "BatBlaster", "TreasurePartyBomb", "Paintbrush", "PvPSword", "PartyPopper", "Coal",
            "FreezeCannon", "Snowball", "Cupid'sArrows", "LovePotion", "ValentinesGift", "HalloweenCandy", "TicTacToe",
            "MobBomb", "PlayCatch", "Trampoline", "Connect4", "Nanny'sUmbrella", "ClackerBoomerang", "GateofBabylon",
            "GrapplingHook", "Spook-in-a-box", "Fromthedepths...", "PortalGun", "SnowGun", "FestiveRelics",
            "ChocolateGun", "LoveLetters", "Jetpack", "Stormbreaker", "BakersDelight", "HumanFirework", "CloneBone",
            "SummoningRitual", "AirSpout", "VillagerMorph", "CowMorph", "ChickenMorph", "BlockMorph", "EndermanMorph",
            "BatMorph", "PumpkinKingsHead", "PigMorph", "CreeperMorph", "BlazeMorph", "WitherMorph", "EasterBunnyMorph",
            "BigLarryMorph", "ElderGuardianMorph", "OlafMorph", "UncleSamMorph", "SquidMorph", "WitchMorph",
            "GrimReaperMorph", "MetalManMorph", "TurkeyMorph", "ChristmasKingsHead", "SantaMorph", "OverEasyMorph",
            "LoveDoctor", "GoldPotMorph", "WascallyWabbitMorph", "BobRossMorph", "FreedomFighter", "MelonheadMorph",
            "HattoriMorph", "DevonMorph", "AnathMorph", "DanaMorph", "BardolfMorph", "RowenaMorph", "LarissaMorph",
            "BiffMorph", "IvyMorph", "GhastMorph", "FrostGolemMorph", "SkeletonMorph", "OcelotMorph", "WolfMorph",
            "PigmanMorph", "GraveMorph", "WinterPrincess", "CraigtheKangaroo", "CupidMorph", "Area51GuardMorph",
            "ShadowWalk", "EmeraldTwirl", "RainCloud", "BloodHelix", "Enchanted", "Music", "PartyTime", "Cupid'sLove",
            "CrushedCandyCane", "WindoftheFrostLord", "LegendaryAura", "FlameoftheTitans", "YinandYang", "King",
            "PixieWings", "DemonWings", "InfernalWings", "AngelWings", "LoveWings", "FlameRings", "FlameFairy",
            "HolidayTree", "CoalFumes", "SpringHalo", "Bumblebee'sWings", "FreedomAura", "FreedomFireworks",
            "StarSpangledStripe", "AuraofNiceness", "CanadianTrail", "HalloweenAura", "ChristmasWings", "BlizzardAura",
            "FidgetSpinnerAura", "PumpkinShield", "RainbowAura", "MacawWings", "ChickenWings", "EnderDragon",
            "FoxTail", "JetPack", "MineplexCape", "LegendaryHero", "WolfTail", "Witch'sCurse", "TrailoftheRainbow",
            "DeepSeaSwirl", "CollidingColors", "FiveYearsofMineplex", "WitherWinds", "IceColdDome",
            "Tis'TheSeasonforHelping", "BeatingHeart", "ClashoftheCakes", "13Disc", "CatDisc", "BlocksDisc",
            "ChirpDisc", "FarDisc", "MallDisc", "MellohiDisc", "StalDisc", "StradDisc", "WardDisc", "WaitDisc",
            "RaveHat", "RaveShirt", "RavePants", "RaveBoots", "SpaceHelmet", "SpaceJacket", "SpacePants", "SpaceBoots",
            "FreezeHelmet", "FreezeChest", "FreezeLeggings", "FreezeBoots", "Leprechaun'sHat", "Leprechaun'sChest",
            "Leprechaun'sPants", "Leprechaun'sBoots", "ReindeerAntlers", "ReindeerChest", "ReindeerLegs",
            "ReindeerHooves", "WindupHelmet", "WindupChestplate", "WindupLeggings", "WindupBoots", "WitchHead",
            "WitchChest", "WitchLegs", "WitchBoots", "TeamHelmet", "TeamShirt", "TeamPants", "TeamBoots",
            "GustoftheFrostLord", "LeapoftheTitans", "CandyCaneBlast", "FirecrackerLeap", "Cupid'sWings", "GreenJump",
            "ShadowLeap", "LeapofWisdom", "WetLeap", "BloodyLeap", "MusicalLeap", "LeapofFreedom", "Trick-Or-Leap",
            "FlowerPower", "MapleLeap", "PresentLeap", "RainbowLeap", "LegendaryLeap", "BalancedLeap",
            "IceColdDoubleJump", "HeartLeap", "ArrowsoftheFrostLord", "ArrowsoftheTitans", "CandyCaneArrows",
            "ArrowConfetti", "Cupid'sArrows", "GreenArrows", "ShadowArrows", "SmartArrows", "RainArrows",
            "BloodyArrows", "MusicArrows", "ShockandAwe", "HalloweenArrows", "FlowerArrows", "Red&WhiteArrows",
            "PresentArrows", "RainbowArrows", "ArrowsoftheLegends", "SimpleGeometry", "IceColdArrowTrail",
            "HeartArrowTrail", "FalloftheFrostLord", "AshesoftheTitans", "CandyCaneRemains", "PinataBurst",
            "Cupid'sBrokenHeart", "GreenDeath", "ShadowDeath", "DeathofWisdom", "GloomyDeath", "GoryBloodDeath",
            "MusicalDeath", "PriceofFreedom", "PresentDanger", "FuneralBouquet", "FallenMapleLeaf", "SpookyDeath",
            "RainbowDeath", "Legend'sLegacy", "Everlastingbalance", "Ghost", "IceColdDeath", "HeartDeath",
            "LumpofCoalHat", "CompanionBlock", "TheGrinch", "LoveStruck", "Present", "Rudolph", "Santa",
            "SecretPackage", "SnowmanHead", "TeddyBear", "UncleSamHat", "PumpkinHat", "WarmCanadianHat",
            "PatrioticAmericanHat", "PottedAzalea", "EternalTaunt", "BlowAKiss", "RainbowTaunt", "InfernalTaunt",
            "FrostBreathTaunt", "EmojiTaunt", "EasyModeTaunt", "ChickenTaunt", "TrickorTreat", "SnowballFight",
            "GloatingGardenerTaunt", "Podium", "MineplexLogo", "Mr.Punchman", "Flames", "SnowTrail", "BabyChicken",
            "LightningStrike", "RiseoftheElderGuardian", "LavaTrap", "ReturnofThePumpkin", "WinterWarfare",
            "LoveisaBattlefield", "Tornado", "Earthquake", "PartyAnimal", "SnowGlobe", "NewYearCelebrations",
            "HoppingSurprise", "UltraWinEffect", "HeroWinEffect", "LegendWinEffect", "TitanWinEffect",
            "EternalWinEffect", "P250Muertos", "CZ75-AutoTigris", "DesertEagleBlaze", "GoldenGun",
            "P2000FireElemental", "Glock18Fade", "NovaKoi", "XM1014Tranquility", "XM1014PigGun", "PP-BizonStreak",
            "P90Asiimov", "FAMASPulse", "M4A4Howl", "EndermanM4", "GalilAREco", "AK-47Vulcan", "GuardianAK",
            "SSG08BloodintheWater", "AWPAsiimov", "SteyrAUGTorque", "SG553Pulse", "M9BayonetFade",
            "CounterTerroristSword", "TerroristSword", "GlassM9Bayonet", "2017ChampionshipKnife",
            "Orange(Bardolf-Werewolf)", "Blue(Bardolf-Werewolf)", "Green(Bardolf-Werewolf)", "Yellow(Bardolf-Werewolf)",
            "Pink(Dana)", "Blue(Dana)", "Brown(Dana)", "Green(Dana)", "Pristine(Dana)", "Wonderful(Dana)",
            "Heroic(Dana)", "Green(Hattori)", "White(Hattori)", "Purple(Hattori)", "Blue(Hattori)", "Red(Larissa)",
            "Pink(Larissa)", "Green(Larissa)", "Yellow(Larissa)", "Green(Biff)", "Purple(Biff)", "Orange(Biff)",
            "Blue(Biff)", "Soulless(Biff)", "Sanctified(Biff)", "BiffSmash!(Biff)", "Demonic(Biff)", "FancyBiff(Biff)",
            "DapperBiff(Biff)", "Brown(Devon)", "Blue(Devon)", "Yellow(Devon)", "Silver(Devon)", "Amethyst(Devon)",
            "Chalk(Devon)", "Orange(Bardolf)", "Blue(Bardolf)", "Green(Bardolf)", "Yellow(Bardolf)", "Purple(Anath)",
            "Yellow(Anath)", "Red(Anath)", "Blue(Anath)", "Light(Anath)", "Shadow(Anath)", "Unburnt(Anath)",
            "CourtMage(Anath)", "MaskedMage(Anath)", "CultMage(Anath)", "Brown(Rowena)", "Blue(Rowena)",
            "Purple(Rowena)", "Red(Rowena)", "Thundercloud(Rowena)", "SheepShopSkin", "CowShopSkin",
            "MooshroomShopSkin", "PigShopSkin", "HorseShopSkin", "SnowmanShopSkin", "IronGolemShopSkin",
            "ZombieShopSkin", "SkeletonShopSkin", "CreeperShopSkin", "SpiderShopSkin", "SlimeShopSkin",
            "MagmaSlimeShopSkin", "WitherSkeletonShopSkin", "PigZombieShopSkin", "WitchShopSkin", "BlazeShopSkin",
            "GuardianShopSkin", "EndermanShopSkin", "SantaShopSkin", "BobRossShopSkin", "FreedomFighterShopSkin",
            "BabyCowBalloon", "BabyPigBalloon", "BabyZombieBalloon", "BabyMushroomCowBalloon", "BabyOcelotBalloon",
            "BabyWolfBalloon", "BabySheepBalloon", "BabyVillagerBalloon", "BabySlimeBalloon", "SquidBalloon",
            "BatBalloon", "SilverfishBalloon", "GuardianBalloon", "DragonEggBalloon", "DiamondBlockBalloon",
            "IronBlockBalloon", "GoldBlockBalloon", "EmeraldBlockBalloon", "RedBalloon", "IceBlockBalloon",
            "CompanionCubeBalloon", "HeartBalloon", "WaterWings", "Halo", "RainbowDance", "RainCloud",
            "ShimmeringRing", "HauntedKit", "BlissfulAstroid", "FlamesOfFury", "Ember", "KitLove", "FlagofCanada",
            "FlagofTheUnitedStatesofAmerica", "FlagofMineplex", "FlagofRudolph", "FlagofChristmasTree",
            "FlagofPresent", "FlagofWreath", "FlagofSnowFlake", "FlagofHeart", "FlagofSpringFlower", "InfernalHorror",
            "GlacialSteed", "MountMule", "EtherealDragon", "SlimeMount", "Minecart", "SpiderMount", "DecrepitWarhorse",
            "MoltenSnake", "BabyReindeer", "LovingSheeples", "FreedomMount", "NightmareSteed", "ChickenMount",
            "CakeMount", "LoveTrain", "RainbowHorse", "PumpkinMount", "SledgeMount", "HeadlessHorseman",
            "SnowmanMount", "Splinter", "Thorn", "Kevin'sLostToothpick", "Striker", "ThornBush", "HowlingSword",
            "QuickBlade", "Winterthorn", "Needle", "Longsword", "Whisper", "Bruiser", "HeartoftheMountain",
            "Quern-Biter", "GravenEdge", "Protector", "GhostReaver", "Skullcrusher", "Ragnarok", "Warmonger",
            "Gutrender", "FrostyGreatsword", "Shadowstrike", "Tenderizer", "GoldDigger", "Peacekeeper", "Gladius",
            "Ghostwalker", "Scar", "Burn", "SunStrike", "MageBlade", "FlamingRapier", "AlienArtifact", "Stormbringer",
            "Sting", "Dragonfire", "Hope'sEnd", "Doombringer", "StormCaller", "BlackOut", "IceHeart", "OoohShiny",
            "Dragonslayer", "Oblivion", "Deathraze", "Oathbreaker", "Vanquisher", "NoblePhantasm", "SweetVictory",
            "RainbowRoad", "No.2Pencil", "GrayLevelColor", "BlueLevelColor", "DarkGreenLevelColor", "GoldLevelColor",
            "RedLevelColor", "DarkRedLevelColor", "YellowLevelColor", "GreenLevelColor", "AquaLevelColor",
            "CyanLevelColor", "DarkBlueLevelColor", "PurpleLevelColor", "PinkLevelColor", "WhiteLevelColor",
            "BlackLevelColor"};

    public static String[] getEnchantments() {
        return ENCHANTMENTS.clone();
    }

    public static String[] getMobs() {
        return MOBS.clone();
    }

    public static String[] getEffects() {
        return EFFECTS.clone();
    }

    public static String[] getMaterials() {
        return MATERIALS.clone();
    }

    public static String[] getCosmetics() {
        return COSMETICS.clone();
    }
}
